steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/for-poc-325210/gcp-automation@sha256::$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/for-poc-325210/gcp-automation@sha256::$SHORT_SHA",
      ]
